// Estilos compartilhados do CardapioBot (tela + componentes extraídos).
import { StyleSheet } from "react-native";

import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  manualToggleRow: {
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 16,
  },
  customizationHeaderText: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  customizationHelper: { fontSize: 13, color: colors.mutedText, marginTop: 4 },
  manualContextWrapper: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#fff",
    maxHeight: 480,
    overflow: "hidden",
  },
  manualContextScroll: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 18,
  },

  heroCard: {
    backgroundColor: colors.primary50,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    gap: 12,
  },
  heroEyebrow: { textTransform: "uppercase", fontSize: 12, color: colors.primary, fontWeight: "700" },
  heroTitle: { fontSize: 20, fontWeight: "700", color: colors.text, marginTop: 4 },
  heroSubtitle: { color: colors.mutedText, marginTop: 6, lineHeight: 18 },

  sectionCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    gap: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: colors.text },
  sectionDescription: { fontSize: 13, color: colors.mutedText },
  sectionLabel: { fontSize: 13, fontWeight: "600", color: colors.mutedText, marginBottom: 6 },

  badgeRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  infoBadge: {
    flex: 1,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  infoBadgeCompact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignSelf: "flex-start",
  },
  infoBadgeWarning: { backgroundColor: "#FEF3C7", borderColor: "#FCD34D" },
  badgeLabel: { fontSize: 12, color: colors.mutedText, textTransform: "uppercase", letterSpacing: 0.5 },
  badgeLabelCompact: { fontSize: 12, fontWeight: "600", color: colors.mutedText, textTransform: "uppercase" },
  badgeValue: { fontSize: 14, fontWeight: "700", color: colors.text, marginTop: 4 },
  badgeValueCompact: { fontSize: 15, fontWeight: "700", color: colors.text },

  expiringRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  expiringName: { fontSize: 14, color: colors.text },
  expiringTag: { fontSize: 13, color: "#B45309", fontWeight: "600" },

  pantryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  pantryPill: {
    width: "48%",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#F3F4F6",
  },
  pantryName: { fontWeight: "600", color: colors.text },
  pantryMeta: { fontSize: 12, color: colors.mutedText, marginTop: 4 },
  pantryEditor: { minHeight: 110, textAlignVertical: "top" },
  helperText: { fontSize: 12, color: colors.mutedText, marginTop: 8, marginBottom: 12 },

  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: "#fff",
  },
  chipActive: { backgroundColor: colors.primary50, borderColor: colors.primary },
  chipText: { color: colors.mutedText, fontSize: 13, fontWeight: "600" },
  chipTextActive: { color: colors.primary },

  textArea: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    backgroundColor: "#fff",
    color: colors.text,
    minHeight: 48,
  },

  inputsRow: { flexDirection: "row", gap: 12, flexWrap: "wrap" },
  inputGroup: { flex: 1, minWidth: 120 },
  inputLabel: { fontSize: 12, color: colors.mutedText, marginBottom: 4 },
  inputBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    backgroundColor: "#fff",
    color: colors.text,
  },

  quickPromptRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  quickPrompt: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#ECFDF5",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  quickPromptText: { color: "#047857", fontWeight: "600", fontSize: 13 },

  lastMenuTitle: { fontSize: 15, fontWeight: "700", color: colors.text },
  lastMenuRange: { fontSize: 13, color: colors.mutedText, marginTop: 2 },
  lastMenuStamp: { fontSize: 12, color: colors.mutedText, marginTop: 6 },

  row: { width: "100%", marginBottom: 12, flexDirection: "row" },
  left: { justifyContent: "flex-start" },
  right: { justifyContent: "flex-end" },

  bubble: {
    maxWidth: "85%",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  botBubble: { backgroundColor: "#f4f6f8" },
  userBubble: { backgroundColor: "#e8f5e9" },

  botName: { color: "#2e7d32", fontWeight: "700", marginBottom: 6 },
  msgText: { fontSize: 15, lineHeight: 20, color: "#222" },
  dot: { width: 6, height: 6, marginRight: 4, borderRadius: 3, backgroundColor: "#999" },

  inputBar: {
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#eee",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fff",
    paddingBottom: 12,
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f5f5f5",
  },
  textInput: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    paddingHorizontal: 10,
    fontSize: 15,
    backgroundColor: "#fff",
    color: colors.text,
  },
  goBtn: {
    paddingHorizontal: 18,
    height: 42,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  goDisabled: { backgroundColor: "#bdbdbd" },
  goText: { color: "#fff", fontWeight: "700" },

  emojiPanel: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#eee",
    backgroundColor: "#fafafa",
    paddingHorizontal: 8,
    paddingTop: 10,
    height: 220,
  },
  emojiTitle: { fontWeight: "700", marginLeft: 4, marginBottom: 6, color: "#333" },
  emojiGrid: { flexDirection: "row", flexWrap: "wrap" },
  emojiBtn: { width: "12.5%", aspectRatio: 1, alignItems: "center", justifyContent: "center" },
  emojiText: { fontSize: 26 },

  menuCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 10,
    width: "100%",
  },
  menuTitle: { fontSize: 16, fontWeight: "700", color: colors.text },
  menuSubtitle: { fontSize: 13, color: colors.mutedText },
  menuConstraintRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  menuConstraintChip: {
    backgroundColor: colors.primary50,
    color: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: "600",
  },
  menuDay: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 10,
  },
  menuDayTitle: { fontWeight: "700", color: colors.text, marginBottom: 6 },
  menuMeal: { marginBottom: 6 },
  menuMealTitle: { fontSize: 13, fontWeight: "600", color: colors.text },
  menuMealText: { fontSize: 12, color: colors.mutedText, marginTop: 2 },
  shoppingBlock: { marginTop: 4 },
  menuSectionLabel: { fontSize: 13, fontWeight: "700", color: colors.text, marginBottom: 6 },
  shoppingRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  shoppingCategory: { fontSize: 13, fontWeight: "600", color: colors.text },
  shoppingItems: { fontSize: 12, color: colors.mutedText, flex: 1, textAlign: "right", marginLeft: 10 },
  assumptionText: { fontSize: 12, color: colors.mutedText, marginTop: 4 },
  menuActions: { marginTop: 8 },
  saveMenuBtn: {
    marginTop: 4,
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  saveMenuBtnDisabled: { opacity: 0.9 },
  saveMenuBtnSaved: {
    backgroundColor: "#f0fdf4",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  saveMenuIcon: { marginRight: 6 },
  saveMenuText: { color: "#fff", fontWeight: "700" },
  saveMenuTextSaved: { color: colors.primary },
  saveMenuHint: { marginTop: 6, fontSize: 11, color: colors.mutedText, textAlign: "center" },
  pdfGenerateButton: {
    marginTop: 12,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pdfGenerateButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
});
